/**
 * The 137 departmental role definitions from the Jennifer Company OS
 * blueprint (Appendix A), as design records. A role is only *ready* when
 * it has an implemented executor, tools, sources, tests, owner and budget;
 * see roles.ts. Generated from the blueprint; edit there, then regenerate.
 */
export type Department =
  | "sales"
  | "deals"
  | "marketing"
  | "operations"
  | "intelligence"
  | "customer"
  | "back_office";
export type RoleMode =
  | "read_analyze"
  | "draft"
  | "controlled_action"
  | "human_decision";
export interface RoleRecord {
  id: string;
  department: Department;
  name: string;
  responsibility: string;
  deliverable: string;
  mode: RoleMode;
  phase: 1 | 2 | 3;
  pilot: boolean;
}

export const ROLE_CATALOG: readonly RoleRecord[] = [
  {
    id: "S01",
    department: "sales",
    name: "Sales coordinator",
    responsibility: "Prioritize the sales queue against capacity and fit",
    deliverable: "Ranked work queue",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "S02",
    department: "sales",
    name: "Ideal customer profile",
    responsibility: "Define segments and explicit exclusion criteria",
    deliverable: "Versioned ICP with scoring rubric",
    mode: "draft",
    phase: 1,
    pilot: true,
  },
  {
    id: "S03",
    department: "sales",
    name: "Lead researcher",
    responsibility:
      "Find organizations using permitted public or licensed sources",
    deliverable: "Source-linked candidate list",
    mode: "read_analyze",
    phase: 1,
    pilot: true,
  },
  {
    id: "S04",
    department: "sales",
    name: "Lead enrichment",
    responsibility: "Add only evidenced business contact and company fields",
    deliverable: "Enriched records with field provenance",
    mode: "read_analyze",
    phase: 1,
    pilot: true,
  },
  {
    id: "S05",
    department: "sales",
    name: "Lead deduplication",
    responsibility:
      "Resolve repeated organizations and contacts before outreach",
    deliverable: "Merge suggestions and canonical IDs",
    mode: "read_analyze",
    phase: 1,
    pilot: true,
  },
  {
    id: "S06",
    department: "sales",
    name: "Contact verifier",
    responsibility:
      "Check addresses and evidence without guessing personal emails",
    deliverable: "Verified or unknown contact status",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "S07",
    department: "sales",
    name: "Account scorer",
    responsibility: "Rank accounts using transparent fit and intent rules",
    deliverable: "Score components and uncertainty",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "S08",
    department: "sales",
    name: "Territory planner",
    responsibility: "Allocate accounts without overlapping owner assignments",
    deliverable: "Territory coverage plan",
    mode: "read_analyze",
    phase: 3,
    pilot: false,
  },
  {
    id: "S09",
    department: "sales",
    name: "Email draft writer",
    responsibility: "Draft relevant first-contact messages with evidence",
    deliverable: "Editable subject and message draft",
    mode: "draft",
    phase: 1,
    pilot: true,
  },
  {
    id: "S10",
    department: "sales",
    name: "Multilingual sales editor",
    responsibility:
      "Adapt approved drafts to English, Portuguese, Spanish or French",
    deliverable: "Localized draft and terminology notes",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "S11",
    department: "sales",
    name: "Personalization reviewer",
    responsibility: "Remove unsupported claims and awkward personalization",
    deliverable: "Reviewed draft with evidence flags",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "S12",
    department: "sales",
    name: "Follow-up planner",
    responsibility: "Plan bounded follow-ups and stop on replies or opt-outs",
    deliverable: "Due dates and draft follow-up tasks",
    mode: "draft",
    phase: 1,
    pilot: true,
  },
  {
    id: "S13",
    department: "sales",
    name: "Outreach dispatcher",
    responsibility:
      "Deliver an approved message through a scoped provider adapter",
    deliverable: "Provider receipt or uncertain status",
    mode: "controlled_action",
    phase: 3,
    pilot: false,
  },
  {
    id: "S14",
    department: "sales",
    name: "Sequence monitor",
    responsibility: "Detect overdue, paused and failed outreach steps",
    deliverable: "Exceptions and next actions",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "S15",
    department: "sales",
    name: "Call preparation",
    responsibility: "Prepare factual agendas and discovery questions",
    deliverable: "Call brief and questions",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "S16",
    department: "sales",
    name: "Discovery guide",
    responsibility:
      "Suggest questions to identify needs without inventing answers",
    deliverable: "Structured discovery checklist",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "S17",
    department: "sales",
    name: "Objection coach",
    responsibility: "Draft responses grounded in approved offer limits",
    deliverable: "Response options with evidence",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "S18",
    department: "sales",
    name: "Opportunity qualifier",
    responsibility: "Recommend qualification status using defined criteria",
    deliverable: "Evidence-backed qualification summary",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "S19",
    department: "sales",
    name: "Referral planner",
    responsibility:
      "Identify appropriate referral asks from existing relationships",
    deliverable: "Referral request drafts",
    mode: "draft",
    phase: 3,
    pilot: false,
  },
  {
    id: "S20",
    department: "sales",
    name: "Reactivation planner",
    responsibility: "Identify eligible dormant accounts and prepare outreach",
    deliverable: "Reactivation draft queue",
    mode: "draft",
    phase: 3,
    pilot: false,
  },
  {
    id: "S21",
    department: "sales",
    name: "Sales forecaster",
    responsibility: "Estimate pipeline outcomes with explicit scenarios",
    deliverable: "Scenario forecast and assumptions",
    mode: "read_analyze",
    phase: 3,
    pilot: false,
  },
  {
    id: "S22",
    department: "sales",
    name: "Sales experiment designer",
    responsibility: "Design measurable tests for offers and messages",
    deliverable: "Experiment brief and stopping rules",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "D01",
    department: "deals",
    name: "Deals coordinator",
    responsibility: "Prioritize opportunities and unresolved blockers",
    deliverable: "Deal action queue",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "D02",
    department: "deals",
    name: "Reply triage",
    responsibility: "Classify intent and stop sequences on replies or opt-outs",
    deliverable: "Intent label, extracted facts and routing",
    mode: "read_analyze",
    phase: 1,
    pilot: true,
  },
  {
    id: "D03",
    department: "deals",
    name: "Response drafter",
    responsibility: "Prepare a factual reply using the latest conversation",
    deliverable: "Editable response draft",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "D04",
    department: "deals",
    name: "Meeting scheduler",
    responsibility: "Book only verified participants and available slots",
    deliverable: "Confirmed event or blocked booking",
    mode: "controlled_action",
    phase: 2,
    pilot: false,
  },
  {
    id: "D05",
    department: "deals",
    name: "Meeting brief",
    responsibility:
      "Summarize a prospect and decisions needed before a meeting",
    deliverable: "One-page meeting brief",
    mode: "read_analyze",
    phase: 1,
    pilot: true,
  },
  {
    id: "D06",
    department: "deals",
    name: "Call summarizer",
    responsibility:
      "Extract decisions and action items from authorized recordings",
    deliverable: "Summary with timestamps and tasks",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "D07",
    department: "deals",
    name: "Action-item tracker",
    responsibility: "Assign and track explicit promises from deal discussions",
    deliverable: "Owner-linked tasks and due dates",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "D08",
    department: "deals",
    name: "Proposal drafter",
    responsibility: "Assemble a proposal using approved scope and pricing",
    deliverable: "Versioned proposal draft",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "D09",
    department: "deals",
    name: "CRM steward",
    responsibility: "Prepare evidence-backed field updates and merge diffs",
    deliverable: "Validated proposed CRM patch",
    mode: "draft",
    phase: 1,
    pilot: true,
  },
  {
    id: "D10",
    department: "deals",
    name: "Pricing scenario analyst",
    responsibility: "Compare approved pricing and margin scenarios",
    deliverable: "Scenario comparison",
    mode: "human_decision",
    phase: 3,
    pilot: false,
  },
  {
    id: "D11",
    department: "deals",
    name: "Negotiation coach",
    responsibility: "Recommend options within documented negotiation authority",
    deliverable: "Options and concession ledger",
    mode: "human_decision",
    phase: 3,
    pilot: false,
  },
  {
    id: "D12",
    department: "deals",
    name: "Contract intake",
    responsibility: "Extract requested terms and route material changes",
    deliverable: "Clause diff and review queue",
    mode: "human_decision",
    phase: 3,
    pilot: false,
  },
  {
    id: "D13",
    department: "deals",
    name: "Document checklist",
    responsibility: "Track missing documents for a decision or onboarding",
    deliverable: "Verified completeness report",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "D14",
    department: "deals",
    name: "Deal-risk reviewer",
    responsibility: "Identify unsupported assumptions and delivery risks",
    deliverable: "Risk register with owners",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "D15",
    department: "deals",
    name: "Pipeline hygiene",
    responsibility:
      "Flag stale stages, missing amounts and contradictory dates",
    deliverable: "Proposed corrections",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "D16",
    department: "deals",
    name: "Deal debrief",
    responsibility: "Analyze won and lost outcomes without guessing causes",
    deliverable: "Evidence-backed lessons",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "D17",
    department: "deals",
    name: "Commitment tracker",
    responsibility: "Maintain promised deliverables and dates across threads",
    deliverable: "Commitment register",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "D18",
    department: "deals",
    name: "Revenue handoff",
    responsibility: "Prepare a verified closed-won handoff to operations",
    deliverable: "Onboarding packet",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "M01",
    department: "marketing",
    name: "Marketing coordinator",
    responsibility:
      "Prioritize content work by audience and measurable objective",
    deliverable: "Weekly content queue",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "M02",
    department: "marketing",
    name: "Brand voice steward",
    responsibility: "Maintain approved voice examples and prohibited claims",
    deliverable: "Versioned voice guide",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "M03",
    department: "marketing",
    name: "Audience researcher",
    responsibility: "Describe audience needs from sourced observations",
    deliverable: "Audience evidence brief",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "M04",
    department: "marketing",
    name: "Content strategist",
    responsibility: "Map audience needs to business objectives and channels",
    deliverable: "Content strategy",
    mode: "draft",
    phase: 2,
    pilot: true,
  },
  {
    id: "M05",
    department: "marketing",
    name: "Editorial planner",
    responsibility: "Build a feasible calendar with owners and dependencies",
    deliverable: "Editorial calendar draft",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "M06",
    department: "marketing",
    name: "Topic researcher",
    responsibility: "Collect sourced facts and questions for an asset",
    deliverable: "Cited research notes",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "M07",
    department: "marketing",
    name: "SEO brief writer",
    responsibility: "Prepare useful search-focused page outlines",
    deliverable: "SEO content brief",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "M08",
    department: "marketing",
    name: "Article drafter",
    responsibility: "Write source-grounded long-form content",
    deliverable: "Article draft with fact references",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "M09",
    department: "marketing",
    name: "Social caption writer",
    responsibility: "Prepare platform-specific captions from approved material",
    deliverable: "Caption variants",
    mode: "draft",
    phase: 2,
    pilot: true,
  },
  {
    id: "M10",
    department: "marketing",
    name: "Video scriptwriter",
    responsibility: "Create scripts with clear hooks and substantiated claims",
    deliverable: "Script and shot notes",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "M11",
    department: "marketing",
    name: "Carousel planner",
    responsibility: "Convert a brief into a clear slide-by-slide story",
    deliverable: "Slide copy and design notes",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "M12",
    department: "marketing",
    name: "Content repurposer",
    responsibility: "Adapt one approved source into several channel formats",
    deliverable: "Repurposed draft pack",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "M13",
    department: "marketing",
    name: "Creative brief writer",
    responsibility: "Define visual direction and deliverable requirements",
    deliverable: "Designer-ready brief",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "M14",
    department: "marketing",
    name: "Landing-page copywriter",
    responsibility: "Draft clear value propositions and calls to action",
    deliverable: "Page copy draft",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "M15",
    department: "marketing",
    name: "Email campaign writer",
    responsibility: "Draft campaigns for eligible audiences",
    deliverable: "Campaign draft set",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "M16",
    department: "marketing",
    name: "Localization editor",
    responsibility: "Adapt marketing assets with language-specific review",
    deliverable: "Localized asset drafts",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "M17",
    department: "marketing",
    name: "Content QA reviewer",
    responsibility: "Check factual support, claims, links and tone",
    deliverable: "Review report and corrected draft",
    mode: "draft",
    phase: 2,
    pilot: true,
  },
  {
    id: "M18",
    department: "marketing",
    name: "Publication dispatcher",
    responsibility: "Publish an exact approved asset to allowed channels",
    deliverable: "Publication receipt or blocked action",
    mode: "controlled_action",
    phase: 3,
    pilot: false,
  },
  {
    id: "M19",
    department: "marketing",
    name: "Campaign analyst",
    responsibility: "Compute campaign results from defined attribution windows",
    deliverable: "Metrics and attribution caveats",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "M20",
    department: "marketing",
    name: "Experiment analyst",
    responsibility: "Assess pre-specified tests and uncertainty",
    deliverable: "Decision report",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "M21",
    department: "marketing",
    name: "Press pitch writer",
    responsibility: "Prepare relevant pitches using approved factual story",
    deliverable: "Press email draft",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "M22",
    department: "marketing",
    name: "Creator researcher",
    responsibility: "Find relevant partners using evidenced audience fit",
    deliverable: "Partner shortlist with sources",
    mode: "read_analyze",
    phase: 3,
    pilot: false,
  },
  {
    id: "M23",
    department: "marketing",
    name: "Reputation monitor",
    responsibility: "Surface relevant public mentions and changes",
    deliverable: "Mention digest and evidence",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "M24",
    department: "marketing",
    name: "Campaign archivist",
    responsibility: "Save approved assets, results and lessons with provenance",
    deliverable: "Searchable campaign record",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "O01",
    department: "operations",
    name: "Operations coordinator",
    responsibility: "Balance queues and surface delivery constraints",
    deliverable: "Cross-team operating plan",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "O02",
    department: "operations",
    name: "Client onboarding",
    responsibility: "Create a checklist from an approved signed scope",
    deliverable: "Owner-linked onboarding plan",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "O03",
    department: "operations",
    name: "Scope checker",
    responsibility: "Compare requested work against agreed deliverables",
    deliverable: "Scope match or change request",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "O04",
    department: "operations",
    name: "Task router",
    responsibility: "Route validated work to an allowed workflow and owner",
    deliverable: "Bounded execution plan",
    mode: "draft",
    phase: 1,
    pilot: true,
  },
  {
    id: "O05",
    department: "operations",
    name: "Project planner",
    responsibility: "Break agreed outcomes into dependencies and milestones",
    deliverable: "Project plan draft",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "O06",
    department: "operations",
    name: "SOP writer",
    responsibility:
      "Convert observed approved procedures into clear instructions",
    deliverable: "Versioned SOP draft",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "O07",
    department: "operations",
    name: "Integration monitor",
    responsibility: "Check connector health without exposing credentials",
    deliverable: "Connection status and repair tasks",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "O08",
    department: "operations",
    name: "Workflow monitor",
    responsibility: "Detect stuck runs and blocked dependencies",
    deliverable: "Exception queue",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "O09",
    department: "operations",
    name: "QA reviewer",
    responsibility: "Check deliverables against explicit acceptance criteria",
    deliverable: "Pass, fail or insufficient evidence",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "O10",
    department: "operations",
    name: "Incident triage",
    responsibility:
      "Classify operational incidents and invoke approved runbooks",
    deliverable: "Incident summary and response tasks",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "O11",
    department: "operations",
    name: "Status reporter",
    responsibility: "Summarize delivery progress with links to work records",
    deliverable: "Stakeholder update draft",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "O12",
    department: "operations",
    name: "Daily executive brief",
    responsibility:
      "Compile company-specific priorities and required decisions",
    deliverable: "Daily brief with evidence and actions",
    mode: "draft",
    phase: 1,
    pilot: true,
  },
  {
    id: "O13",
    department: "operations",
    name: "Capacity planner",
    responsibility: "Compare commitments against available delivery capacity",
    deliverable: "Capacity scenarios",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "O14",
    department: "operations",
    name: "Dependency tracker",
    responsibility: "Detect blocked work and contradictory dependency graphs",
    deliverable: "Blocker list and owner requests",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "O15",
    department: "operations",
    name: "Handoff reviewer",
    responsibility: "Verify outputs meet the receiving team's requirements",
    deliverable: "Accepted handoff or missing-field list",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "O16",
    department: "operations",
    name: "Vendor evaluator",
    responsibility: "Compare suppliers against documented requirements",
    deliverable: "Sourced comparison",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "O17",
    department: "operations",
    name: "Procurement drafter",
    responsibility: "Prepare purchase requests with limits and approvals",
    deliverable: "Purchase request draft",
    mode: "draft",
    phase: 3,
    pilot: false,
  },
  {
    id: "O18",
    department: "operations",
    name: "Access reviewer",
    responsibility: "Recommend least-privilege access changes for owners",
    deliverable: "Review report with exact scope diffs",
    mode: "draft",
    phase: 3,
    pilot: false,
  },
  {
    id: "O19",
    department: "operations",
    name: "Data-quality monitor",
    responsibility: "Find missing provenance, broken links and invalid fields",
    deliverable: "Data-quality exception queue",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "O20",
    department: "operations",
    name: "Release coordinator",
    responsibility: "Assemble release evidence and propose rollout steps",
    deliverable: "Release checklist and rollback plan",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "O21",
    department: "operations",
    name: "Retention operator",
    responsibility: "Execute approved data-retention and deletion jobs",
    deliverable: "Deletion receipt and audit record",
    mode: "controlled_action",
    phase: 3,
    pilot: false,
  },
  {
    id: "O22",
    department: "operations",
    name: "Continuity planner",
    responsibility: "Prepare recovery exercises and operational fallback plans",
    deliverable: "Exercise plan and gaps",
    mode: "draft",
    phase: 3,
    pilot: false,
  },
  {
    id: "I01",
    department: "intelligence",
    name: "Intelligence coordinator",
    responsibility: "Prioritize research questions and avoid duplicate work",
    deliverable: "Research agenda",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "I02",
    department: "intelligence",
    name: "Company researcher",
    responsibility: "Build a sourced account brief from permitted evidence",
    deliverable: "Cited facts, gaps and dated sources",
    mode: "read_analyze",
    phase: 1,
    pilot: true,
  },
  {
    id: "I03",
    department: "intelligence",
    name: "Competitor researcher",
    responsibility: "Compare documented competitor offers and positioning",
    deliverable: "Dated competitive brief",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "I04",
    department: "intelligence",
    name: "Market mapper",
    responsibility: "Organize a market by geography and customer segment",
    deliverable: "Evidence-linked market map",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "I05",
    department: "intelligence",
    name: "Signal monitor",
    responsibility:
      "Detect defined changes in allowed public or licensed feeds",
    deliverable: "Dated signals and affected entities",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "I06",
    department: "intelligence",
    name: "Trend analyst",
    responsibility: "Distinguish observed trends from weak anecdotes",
    deliverable: "Trend report with uncertainty",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "I07",
    department: "intelligence",
    name: "Opportunity screener",
    responsibility: "Rank opportunities using explicit assumptions",
    deliverable: "Screening table and missing evidence",
    mode: "human_decision",
    phase: 3,
    pilot: false,
  },
  {
    id: "I08",
    department: "intelligence",
    name: "Location researcher",
    responsibility: "Compare locations using requested observable criteria",
    deliverable: "Sourced location comparison",
    mode: "read_analyze",
    phase: 3,
    pilot: false,
  },
  {
    id: "I09",
    department: "intelligence",
    name: "Due-diligence organizer",
    responsibility: "Assemble requested evidence and unresolved questions",
    deliverable: "Indexed diligence packet",
    mode: "human_decision",
    phase: 3,
    pilot: false,
  },
  {
    id: "I10",
    department: "intelligence",
    name: "Source verifier",
    responsibility: "Check origin, recency and corroboration of claims",
    deliverable: "Source-quality annotations",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "I11",
    department: "intelligence",
    name: "Regulatory change monitor",
    responsibility: "Identify possible relevant changes for qualified review",
    deliverable: "Dated change alert and review task",
    mode: "human_decision",
    phase: 3,
    pilot: false,
  },
  {
    id: "I12",
    department: "intelligence",
    name: "Grant researcher",
    responsibility: "Find eligible-looking opportunities and actual deadlines",
    deliverable: "Cited grant shortlist",
    mode: "read_analyze",
    phase: 3,
    pilot: false,
  },
  {
    id: "I13",
    department: "intelligence",
    name: "Partnership researcher",
    responsibility: "Find organizations with complementary interests",
    deliverable: "Partner shortlist",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "I14",
    department: "intelligence",
    name: "Customer insight analyst",
    responsibility: "Extract themes from authorized feedback",
    deliverable: "Theme report with anonymized evidence",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "I15",
    department: "intelligence",
    name: "Pricing researcher",
    responsibility: "Collect comparable published pricing with caveats",
    deliverable: "Dated pricing comparison",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "I16",
    department: "intelligence",
    name: "Experiment researcher",
    responsibility: "Design research that can disprove a business assumption",
    deliverable: "Research protocol and decision threshold",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "I17",
    department: "intelligence",
    name: "Knowledge curator",
    responsibility: "Propose knowledge updates with provenance and expiry",
    deliverable: "Reviewable knowledge patch",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "I18",
    department: "intelligence",
    name: "Decision memo writer",
    responsibility: "Present options, evidence, assumptions and open questions",
    deliverable: "Decision memo for accountable owner",
    mode: "human_decision",
    phase: 2,
    pilot: false,
  },
  {
    id: "C01",
    department: "customer",
    name: "Customer coordinator",
    responsibility: "Prioritize support work using severity and commitments",
    deliverable: "Assigned support plan",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "C02",
    department: "customer",
    name: "Support triage",
    responsibility: "Classify requests and identify urgent or sensitive cases",
    deliverable: "Category, severity and route",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "C03",
    department: "customer",
    name: "FAQ responder",
    responsibility: "Draft answers only from current approved knowledge",
    deliverable: "Answer with evidence or escalation",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "C04",
    department: "customer",
    name: "Troubleshooting guide",
    responsibility: "Guide reversible diagnostic steps from approved runbooks",
    deliverable: "Diagnostic steps and outcomes",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "C05",
    department: "customer",
    name: "Ticket router",
    responsibility: "Assign work to the appropriate permitted team",
    deliverable: "Routing decision and task",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "C06",
    department: "customer",
    name: "Escalation coordinator",
    responsibility: "Prepare a complete escalation when limits are reached",
    deliverable: "Escalation packet",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "C07",
    department: "customer",
    name: "SLA monitor",
    responsibility: "Track response deadlines and warn responsible owners",
    deliverable: "Due-time alerts",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "C08",
    department: "customer",
    name: "Resolution drafter",
    responsibility: "Draft a clear answer explaining verified resolution",
    deliverable: "Customer response draft",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "C09",
    department: "customer",
    name: "Feedback collector",
    responsibility: "Prepare appropriately scoped feedback requests",
    deliverable: "Survey or interview draft",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "C10",
    department: "customer",
    name: "Satisfaction analyst",
    responsibility: "Summarize measured satisfaction and sample limitations",
    deliverable: "Satisfaction report",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "C11",
    department: "customer",
    name: "Customer health analyst",
    responsibility: "Calculate transparent indicators using available evidence",
    deliverable: "Health factors with unknown fields",
    mode: "read_analyze",
    phase: 3,
    pilot: false,
  },
  {
    id: "C12",
    department: "customer",
    name: "Renewal planner",
    responsibility: "Track renewal dates and prepare account review tasks",
    deliverable: "Renewal work queue",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "C13",
    department: "customer",
    name: "Churn signal reviewer",
    responsibility: "Surface interpretable warning signs for human review",
    deliverable: "Risk signals and uncertainty",
    mode: "read_analyze",
    phase: 3,
    pilot: false,
  },
  {
    id: "C14",
    department: "customer",
    name: "Retention drafter",
    responsibility: "Draft approved retention options within service limits",
    deliverable: "Retention response options",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "C15",
    department: "customer",
    name: "Expansion researcher",
    responsibility: "Identify relevant additional needs without inventing them",
    deliverable: "Evidence-backed expansion suggestions",
    mode: "read_analyze",
    phase: 3,
    pilot: false,
  },
  {
    id: "C16",
    department: "customer",
    name: "Community moderator",
    responsibility: "Suggest moderation actions under a written policy",
    deliverable: "Review queue and rationale",
    mode: "draft",
    phase: 3,
    pilot: false,
  },
  {
    id: "C17",
    department: "customer",
    name: "Knowledge-gap finder",
    responsibility: "Detect common unanswered questions and stale help",
    deliverable: "Knowledge improvement backlog",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "C18",
    department: "customer",
    name: "Customer insight reporter",
    responsibility: "Summarize customer themes for product and operations",
    deliverable: "Prioritized insight digest",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "B01",
    department: "back_office",
    name: "Back-office coordinator",
    responsibility: "Prioritize administrative work and owner decisions",
    deliverable: "Administrative work plan",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "B02",
    department: "back_office",
    name: "Invoice drafter",
    responsibility: "Prepare invoice fields from an approved commercial record",
    deliverable: "Invoice draft with source references",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "B03",
    department: "back_office",
    name: "Receivables tracker",
    responsibility: "Reconcile open receivables against confirmed receipts",
    deliverable: "Aging report and discrepancies",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "B04",
    department: "back_office",
    name: "Payment reminder drafter",
    responsibility: "Draft accurate reminders for confirmed unpaid invoices",
    deliverable: "Reminder draft",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "B05",
    department: "back_office",
    name: "Expense categorizer",
    responsibility:
      "Propose categories and flag uncertain accounting treatment",
    deliverable: "Category suggestions and exceptions",
    mode: "human_decision",
    phase: 3,
    pilot: false,
  },
  {
    id: "B06",
    department: "back_office",
    name: "Reconciliation assistant",
    responsibility: "Match records deterministically and expose differences",
    deliverable: "Matches and unresolved exceptions",
    mode: "read_analyze",
    phase: 3,
    pilot: false,
  },
  {
    id: "B07",
    department: "back_office",
    name: "Financial report assembler",
    responsibility: "Compile reviewed numbers into reporting templates",
    deliverable: "Report draft with linked calculations",
    mode: "human_decision",
    phase: 3,
    pilot: false,
  },
  {
    id: "B08",
    department: "back_office",
    name: "Cash-flow scenario analyst",
    responsibility: "Calculate cash scenarios from explicit assumptions",
    deliverable: "Scenario forecast",
    mode: "human_decision",
    phase: 3,
    pilot: false,
  },
  {
    id: "B09",
    department: "back_office",
    name: "Budget variance analyst",
    responsibility:
      "Compare actuals and budget using reproducible calculations",
    deliverable: "Variance report",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "B10",
    department: "back_office",
    name: "Contract organizer",
    responsibility: "Index obligations and dates from approved contracts",
    deliverable: "Contract register with citations",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "B11",
    department: "back_office",
    name: "Renewal calendar",
    responsibility: "Track contract notice periods and renewal deadlines",
    deliverable: "Renewal tasks and alerts",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
  {
    id: "B12",
    department: "back_office",
    name: "Payroll input checker",
    responsibility: "Check completeness of inputs for the payroll provider",
    deliverable: "Exceptions for authorized payroll owner",
    mode: "human_decision",
    phase: 3,
    pilot: false,
  },
  {
    id: "B13",
    department: "back_office",
    name: "Tax document organizer",
    responsibility: "Assemble records requested by the accountant",
    deliverable: "Indexed accountant packet",
    mode: "human_decision",
    phase: 3,
    pilot: false,
  },
  {
    id: "B14",
    department: "back_office",
    name: "Management pack writer",
    responsibility: "Explain reviewed metrics and unresolved assumptions",
    deliverable: "Management briefing draft",
    mode: "draft",
    phase: 2,
    pilot: false,
  },
  {
    id: "B15",
    department: "back_office",
    name: "Audit evidence assembler",
    responsibility: "Collect authorized evidence for a defined audit request",
    deliverable: "Evidence index with provenance",
    mode: "read_analyze",
    phase: 2,
    pilot: false,
  },
];
