import * as SecureStore from 'expo-secure-store';
const base=(process.env.EXPO_PUBLIC_JENNIFER_API_URL??'').replace(/\/$/,'');
const KEY='jennifer.session.token';
export const saveToken=(v:string)=>SecureStore.setItemAsync(KEY,v);
export const clearToken=()=>SecureStore.deleteItemAsync(KEY);
export const hasToken=async()=>!!(await SecureStore.getItemAsync(KEY));
async function request<T>(path:string,init:RequestInit={}):Promise<T>{if(!base)throw new Error('Set EXPO_PUBLIC_JENNIFER_API_URL');const token=await SecureStore.getItemAsync(KEY);const res=await fetch(base+path,{...init,headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{}),...(init.headers||{})}});const text=await res.text();if(!res.ok)throw new Error(text||('HTTP '+res.status));return text?JSON.parse(text):{} as T;}
const post=(path:string,body:unknown={})=>request<any>(path,{method:'POST',body:JSON.stringify(body)});
export const JenniferAPI={health:()=>request<{ok:boolean}>('/health'),today:()=>request<any>('/v1/today'),actions:(state?:string)=>request<any>('/v1/actions'+(state?'?state='+encodeURIComponent(state):'')),action:(id:string)=>request<any>('/v1/actions/'+id),approve:(id:string,revision:number,payloadHash:string)=>post('/v1/actions/'+id+'/approve',{revision,payloadHash}),cancel:(id:string,note='Canceled from mobile')=>post('/v1/actions/'+id+'/cancel',{note}),conversations:()=>request<any[]>('/v1/conversations'),conversation:(id:string)=>request<any>('/v1/conversations/'+id),missions:()=>request<any>('/v1/missions'),runMission:(id:string)=>post('/v1/missions/'+id+'/run',{mode:'work',reason:'Requested from Jennifer Mobile'}),voice:()=>request<any>('/v1/voice'),notificationPrefs:()=>request<any>('/v1/notifications/prefs'),memoryPending:()=>request<any[]>('/v1/memory/pending'),activateMemory:(id:string)=>post('/v1/memory/'+id+'/activate'),chat:(message:string,sessionId?:string)=>post('/v1/chat',{message,sessionId}),logout:()=>post('/v1/auth/logout')};
